apiVersion: projectcalico.org/v3
kind: GlobalNetworkPolicy
metadata:
  name: csusb-trusted-nodes
spec:
  order: 11
  preDNAT: true
  applyOnForward: true
  ingress:
    - action: Allow
      source:
        selector: role == 'csusb-trusted'
  selector: csusb-trusted == 'true'
---
apiVersion: projectcalico.org/v3
kind: GlobalNetworkSet
metadata:
  name: production-nodes
  labels:
    role: csusb-trusted
spec:
  nets:
  - 139.182.0.0/16   #san bernardino
  - 198.188.128.0/22 #palm desert
  - 10.0.0.0/8       #internal nat, mostly 10.120.0.0/13
  - 134.71.3.19/32   #scuffy.wrccdc.cpp.edu
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: perfsonar.csusb.edu
  labels:
    host-endpoint: production
    csusb-trusted: "true"
    globus: "true"
spec:
  node: perfsonar.csusb.edu
  expectedIPs:
  - 139.182.103.10
