apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-20
  labels:
    host-endpoint: production
spec:
  node: suncave-20
  expectedIPs:
  - 67.58.51.58
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-21
  labels:
    host-endpoint: production
spec:
  node: suncave-21
  expectedIPs:
  - 67.58.51.59
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-22
  labels:
    host-endpoint: production
spec:
  node: suncave-22
  expectedIPs:
  - 67.58.51.60
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-23
  labels:
    host-endpoint: production
spec:
  node: suncave-23
  expectedIPs:
  - 67.58.51.61
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-24
  labels:
    host-endpoint: production
spec:
  node: suncave-24
  expectedIPs:
  - 67.58.51.62

---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-25
  labels:
    host-endpoint: production
spec:
  node: suncave-25
  expectedIPs:
  - 67.58.51.10
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-26
  labels:
    host-endpoint: production
spec:
  node: suncave-26
  expectedIPs:
  - 67.58.51.11
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-27
  labels:
    host-endpoint: production
spec:
  node: suncave-27
  expectedIPs:
  - 67.58.51.12
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-28
  labels:
    host-endpoint: production
spec:
  node: suncave-28
  expectedIPs:
  - 67.58.51.13
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-29
  labels:
    host-endpoint: production
spec:
  node: suncave-29
  expectedIPs:
  - 67.58.51.14
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-30
  labels:
    host-endpoint: production
spec:
  node: suncave-30
  expectedIPs:
  - 67.58.51.15
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-31
  labels:
    host-endpoint: production
spec:
  node: suncave-31
  expectedIPs:
  - 67.58.51.16
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-32
  labels:
    host-endpoint: production
spec:
  node: suncave-32
  expectedIPs:
  - 67.58.51.17
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-33
  labels:
    host-endpoint: production
spec:
  node: suncave-33
  expectedIPs:
  - 67.58.51.18
---
apiVersion: projectcalico.org/v3
kind: HostEndpoint
metadata:
  name: suncave-34
  labels:
    host-endpoint: production
spec:
  node: suncave-34
  expectedIPs:
  - 67.58.51.19
