apiVersion: v1
kind: Pod
metadata:
  name: nfscli2
  namespace: default
spec:
  containers:
  - name: test
    image: centos
    args: ["sleep", "infinity"]
    volumeMounts:
    - name: nfs
      mountPath: /nfs
  volumes:
  - name: nfs
    nfs:
      server: <ip>
      path: "/"
