apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: myazdani
  namespace: nfs-servers
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: myazdani
  namespace: nfs-servers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: myazdani-nfs
    spec:
      containers:
      - name: nfs
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        env:
          - name: SHARED_DIRECTORY
            value: /data
        image: itsthenetwork/nfs-server-alpine
        args: ["sleep", "infinity"]
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: myazdani
---
apiVersion: v1
kind: Service
metadata:
  name: myazdani
  namespace: nfs-servers
  labels:
    k8s-app: myazdani-nfs
spec:
  ports:
  - port: 111
    name: portmapper
  - port: 2049
    name: nfs
  selector:
    k8s-app: myazdani-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: myazdani-pv
  labels:
    project: myazdani
spec:
  storageClassName: nfs
  mountOptions: 
    - soft
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: <ip>
    path: /
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: myazdani-pv
  namespace: myazdani
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      project: myazdani