apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oliver
  namespace: nfs-servers
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: oliver
  namespace: nfs-servers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: oliver-nfs
    spec:
      containers:
      - name: nfs
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        env:
          - name: SHARED_DIRECTORY
            value: /data
        image: itsthenetwork/nfs-server-alpine
        args: ["sleep", "infinity"]
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: oliver
---
apiVersion: v1
kind: Service
metadata:
  name: oliver
  namespace: nfs-servers
  labels:
    k8s-app: oliver-nfs
spec:
  ports:
  - port: 111
    name: portmapper
  - port: 2049
    name: nfs
  selector:
    k8s-app: oliver-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-pv
  namespace: wiki
  labels:
    project: wiki
spec:
  storageClassName: nfs
  mountOptions: 
    - soft
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: <ip>
    path: /
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wiki-backups-pv
  namespace: wiki-backups
  labels:
    project: wiki-backups
spec:
  storageClassName: nfs
  mountOptions: 
    - soft
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: <ip>
    path: /
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nacre-pv
  namespace: nacre
  labels:
    project: nacre
spec:
  storageClassName: nfs
  mountOptions: 
    - soft
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.107.66.160
    path: /
