apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subflow
  namespace: nfs-servers
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: subflow
  namespace: nfs-servers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: subflow-nfs
    spec:
      containers:
      - name: nfs
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        env:
          - name: SHARED_DIRECTORY
            value: /data
        image: itsthenetwork/nfs-server-alpine
        args: ["sleep", "infinity"]
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: subflow
---
apiVersion: v1
kind: Service
metadata:
  name: subflow
  namespace: nfs-servers
  labels:
    k8s-app: subflow-nfs
spec:
  ports:
  - port: 111
    name: portmapper
  - port: 2049
    name: nfs
  selector:
    k8s-app: subflow-nfs
