apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: words-geo
  namespace: nfs-servers
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: words-geo
  namespace: nfs-servers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: words-geo-nfs
    spec:
      containers:
      - name: nfs
        securityContext:
          capabilities:
            add: ["SYS_ADMIN"]
        env:
          - name: SHARED_DIRECTORY
            value: /data
        image: itsthenetwork/nfs-server-alpine
        args: ["sleep", "infinity"]
        volumeMounts:
        - mountPath: /data
          name: data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: words-geo
---
apiVersion: v1
kind: Service
metadata:
  name: words-geo
  namespace: nfs-servers
  labels:
    k8s-app: words-geo-nfs
spec:
  ports:
  - port: 111
    name: portmapper
  - port: 2049
    name: nfs
  selector:
    k8s-app: words-geo-nfs
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: words-geo-pv
  namespace: words-geo
  labels:
    project: words-geo
spec:
  storageClassName: nfs
  mountOptions: 
    - soft
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: <ip>
    path: /web
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: words-geo-pv
  namespace: words-geo
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      project: words-geo
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: words-geocolor-pv
  namespace: words-geo
  labels:
    project: words-geocolor
spec:
  storageClassName: nfs
  mountOptions: 
    - soft
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  nfs:
    server: <ip>
    path: /
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: words-geocolor-pv
  namespace: words-geo
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  selector:
    matchLabels:
      project: words-geocolor