apiVersion: ceph.rook.io/v1beta1
kind: Filesystem
metadata:
  name: nautilusfs
  namespace: rook
spec:
  metadataPool:
    replicated:
      size: 3
  dataPools:
    - erasureCoded:
        dataChunks: 3
        codingChunks: 2
  metadataServer:
    activeCount: 2
    activeStandby: true
    placement:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - production
            - key: nw
              operator: In
              values:
              - 100G
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - rook-ceph-mds
            topologyKey: kubernetes.io/hostname
          weight: 100              
    resources:
     limits:
       memory: "16Gi"
     requests:
       memory: "4Gi"
