apiVersion: v1
kind: Namespace
metadata:
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: monitor=true
  name: rook
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  monCount: 5
  dataDirHostPath: /var/lib/rook
  storage:                # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    metadataDevice:
    location:
    storeConfig:
      storeType: bluestore
    nodes:
    - name: "k8s-gpu-03.sdsc.optiputer.net"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "sde"
      - name: "sdf"
    - name: "fiona.nwsc.ucar.edu"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
    - name: "k8s-epyc-01.sdsc.optiputer.net"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
      - name: "sde" #480GB SSD
      - name: "sdf" #480GB SSD
      - name: "sdg" #10TB SAS3
      - name: "sdh" #10TB SAS3
      - name: "sdi" #10TB SAS3
      - name: "sdj" #10TB SAS3
      - name: "sdk" #10TB SAS3
      - name: "sdl" #10TB SAS3
      - name: "sdm" #10TB SAS3
      - name: "sdn" #10TB SAS3
    - name: "k8s-nvme-01.sdsc.optiputer.net"
      devices:
      # sda,sdb boot
   #  - name: "nvme0n1" Docker ZFS
   #  - name: "nvme1n1" Docker ZFS
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
      - name: "sdc"
      - name: "sdd"
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
    - name: "fiona.tools.ucla.net"
      devices:
      # sda,sdb boot
   #  - name: "nvme0n1" Docker ZFS
      - name: "sdc"
      - name: "sdd"
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
    - name: "fiona-dtn-1.ucsc.edu"
      devices:
      # sdq,sdah boot
      # sdr,sds docker
      - name: "sdt"
      - name: "sdu"
      - name: "sdv"
      - name: "sdw"
      - name: "sdx"
      - name: "sdy"
      - name: "sdz"
      - name: "sdaa"
      - name: "sdab"
      - name: "sdac"
      - name: "sdad"
      - name: "sdae"
      - name: "sdaf"
      - name: "sdag"
    - name: "ps-100g.sdsu.edu"
      devices:
      # sdc,sdd boot
      # sda,sdb docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
    - name: "siderea.ucsc.edu"
      devices:
      # sdc,sdd boot
      # sda,sdb docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
    - name: "fiona-dtn.usc.edu"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
    - name: "k8s-nvme-01.ultralight.org"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
      - name: "sde"
    - name: "netw-fiona.stanford.edu"
      devices:
      # sdc,sdd boot
      # sda,sdb docker
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
      - name: "sds"
      - name: "sdt"
    - name: "fiona.its.hawaii.edu"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
    - name: "dtn-main.ucr.edu"
      devices:
      # sdr,sds boot
      # sda docker
      - name: "sdb"
      - name: "sdc"
      - name: "sdd"
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdn"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
    - name: "knuron.calit2.optiputer.net"
      devices:
      # sdj,sdk boot
      # sda docker
      - name: "sdb"
      - name: "sdc"
      - name: "sdd"
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
   #  - name: "k8s-gpu-02.calit2.optiputer.net"
   #    devices:
   #    # sda,sdb boot
   #    # sdc,sdd docker
   #    - name: "nvme0n1"
   #    - name: "nvme1n1"
   #    - name: "sde"
   #    - name: "sdf"
   #  - name: "dtn2-daejeon.kreonet.net"
   #    devices:
   #    # sda boot  #500GB SSD
   #    # sdb,sdc docker  #2x 1TB SSD
   #    - name: "sdd" #1TB SSD
   #    - name: "sde" #1TB SSD
   #    - name: "sdf" #4TB SATA
   #    - name: "sdg" #4TB SATA
   #    - name: "sdh" #4TB SATA
   #    - name: "sdi" #4TB SATA
   #    - name: "sdj" #4TB SATA
   #    - name: "sdk" #4TB SATA
  # - name: "fiona8.calit2.uci.edu"
  #   devices:
  #   - name: "nvme0n1"
  #   - name: "nvme1n1"
  #   - name: "sdd"
  #   - name: "sde"
  #   - name: "sdf"
  # - name: "prp-dtn.noc.ucsb.edu"
  #   devices:
  #   # sda DEAD
  #   # sdb docker
  #   # sdc boot
  #   # sdd spare SATA DOM
  #   - name: "sde" #10TB 
  #   - name: "sdf" #10TB 
  #   - name: "sdg" #10TB 
  #   - name: "sdh" #10TB 
  #   - name: "sdi" # 128GB ?? Missed a disk
  #   - name: "sdj" #10TB 
  #   - name: "sdk" #10TB 
  #   - name: "sdl" #10TB 
  #   - name: "sdm" #10TB 
  #   - name: "sdn" #10TB 
  #   - name: "sdo" #10TB 
  #   - name: "sdp" #10TB 
  #   - name: "sdq" #10TB 
  #   - name: "sdr" #10TB 
  #   - name: "sds" #10TB 
  #   - name: "sdt" #10TB 
