apiVersion: v1
kind: Namespace
metadata:
  name: rook
---
apiVersion: rook.io/v1alpha1
kind: Cluster
metadata:
  name: rook
  namespace: rook
spec:
  monCount: 5
  dataDirHostPath: /var/lib/rook
  placement:
    api:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - production
    mgr:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - production
    mon:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: env
              operator: In
              values:
              - production
    osd:
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "PreferNoSchedule"        
      - key: "hawaiiRegion"
        operator: "Exists"
        effect: "PreferNoSchedule"        
  storage:                # cluster level storage configuration and selection
    useAllNodes: false
    useAllDevices: false
    deviceFilter:
    metadataDevice:
    location:
    storeConfig:
      storeType: bluestore
    nodes:
    - name: "fiona.nwsc.ucar.edu"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
      resources:
        requests:
          memory: "3Gi"
        limits:
          memory: "15Gi"
    - name: "k8s-epyc-01.sdsc.optiputer.net"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
      - name: "sde" #480GB SSD
      - name: "sdf" #480GB SSD
      - name: "sdg" #10TB SAS3
      - name: "sdh" #10TB SAS3
      - name: "sdi" #10TB SAS3
      - name: "sdj" #10TB SAS3
      - name: "sdk" #10TB SAS3
      - name: "sdl" #10TB SAS3
      - name: "sdm" #10TB SAS3
      - name: "sdn" #10TB SAS3
      resources:
        requests:
          memory: "4Gi"
        limits:
          memory: "15Gi"
    - name: "k8s-nvme-01.sdsc.optiputer.net"
      devices:
      # sda,sdb boot
   #  - name: "nvme0n1" Docker ZFS
   #  - name: "nvme1n1" Docker ZFS
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
      - name: "sdc"
      - name: "sdd"
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      resources:
        requests:
          memory: "3Gi"
        limits:
          memory: "15Gi"
    - name: "fiona.tools.ucla.net"
      devices:
      # sda,sdb boot
   #  - name: "nvme0n1" Docker ZFS
   # one drive removed
      - name: "sdc"
      - name: "sdd"
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
      resources:
        requests:
          memory: "3Gi"
        limits:
          memory: "15Gi"
    - name: "fiona-dtn-1.ucsc.edu"
      devices:
      # sdq,sdah boot
      # sdr,sds docker
      - name: "sdt"
      - name: "sdu"
      - name: "sdv"
      - name: "sdw"
      - name: "sdx"
      - name: "sdy"
      - name: "sdz"
      - name: "sdaa"
      - name: "sdab"
      - name: "sdac"
      - name: "sdad"
      - name: "sdae"
      - name: "sdaf"
      - name: "sdag"
      resources:
        requests:
          memory: "5Gi"
        limits:
          memory: "15Gi"
    - name: "ps-100g.sdsu.edu"
      devices:
      # sdc,sdd boot
      # sda,sdb docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
      resources:
        requests:
          memory: "5Gi"
        limits:
          memory: "15Gi"
    - name: "siderea.ucsc.edu"
      devices:
      # sdc,sdd boot
      # sda,sdb docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
      resources:
        requests:
          memory: "5Gi"
        limits:
          memory: "15Gi"
    - name: "hydra.gi.ucsc.edu"
      devices:
      # sdi,sdj boot
      # nvme0n1 docker 3.2TB
      #- name: "sda" #480GB SSD Ceph Journal ?
      - name: "sdb" #480GB SSD
      - name: "sdc" #480GB SSD
      - name: "sdd" #480GB SSD
      - name: "sde" #480GB SSD
      - name: "sdf" #480GB SSD
      - name: "sdg" #480GB SSD
      - name: "sdh" #480GB SSD
      resources:
        requests:
          memory: "5Gi"
        limits:
          memory: "15Gi"          
    - name: "fiona-dtn.usc.edu"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
      resources:
        requests:
          memory: "2Gi"
        limits:
          memory: "15Gi"
    - name: "k8s-nvme-01.ultralight.org"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      - name: "nvme4n1"
      - name: "nvme5n1"
      - name: "nvme6n1"
      - name: "nvme7n1"
      - name: "sde"
      resources:
        requests:
          memory: "4Gi"
        limits:
          memory: "15Gi"
    - name: "netw-fiona.stanford.edu"
      devices:
      # sdc,sdd boot
      # sda,sdb docker
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
      - name: "sds"
      - name: "sdt"
      resources:
        requests:
          memory: "4Gi"
        limits:
          memory: "15Gi"
    - name: "fiona.its.hawaii.edu"
      devices:
      # sda,sdb boot
      # sdc,sdd docker
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdm"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      - name: "sdr"
      resources:
        requests:
          memory: "3Gi"
        limits:
          memory: "15Gi"
    - name: "dtn-main.ucr.edu"
      devices:
      # sdr,sds boot
      # sda docker
      - name: "sdb"
      - name: "sdc"
      - name: "sdd"
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "sdj"
      - name: "sdk"
      - name: "sdl"
      - name: "sdn"
      - name: "sdn"
      - name: "sdo"
      - name: "sdp"
      - name: "sdq"
      resources:
        requests:
          memory: "3Gi"
        limits:
          memory: "15Gi"
    - name: "knuron.calit2.optiputer.net"
      devices:
      # sdj,sdk boot
      # sda docker
      - name: "sdb"
      - name: "sdc"
      - name: "sdd"
      - name: "sde"
      - name: "sdf"
      - name: "sdg"
      - name: "sdh"
      - name: "sdi"
      - name: "nvme0n1"
      - name: "nvme1n1"
      - name: "nvme2n1"
      - name: "nvme3n1"
      resources:
        requests:
          memory: "4Gi"
        limits:
          memory: "15Gi"
    # - name: "fiona.oit.uci.edu"
    #   devices:
    #   # sda,sdb boot
    #   # nvme0n1 docker
    #   - name: "sde" #12TB 
    #   - name: "sdae" #12TB
    #   - name: "sdr" #12TB
    #   - name: "sdad" #12TB
    #   - name: "sdq" #12TB
    #   - name: "sdv" #12TB
    #   - name: "sdg" #12TB
    #   - name: "sdp" #12TB
    #   - name: "sdt" #12TB
    #   - name: "sdh" #12TB
    #   - name: "sdac" #12TB
    #   - name: "sds" #12TB
    #   - name: "sdi" #12TB
    #   - name: "sdl" #12TB
    #   - name: "sdaa" #12TB
    #   - name: "sdj" #12TB


    # - name: "k8s-gpu-03.sdsc.optiputer.net"
    #   devices:
    #   # sda,sdb boot
    #   # sdc,sdd docker
    #   - name: "nvme0n1"
    #   - name: "nvme1n1"
    #   - name: "sde"
    #   - name: "sdf"

      
    # - name: "k8s-gpu-02.calit2.optiputer.net"
    #   devices:
    #   # sda,sdb boot
    #   # sdc,sdd docker
    #   - name: "nvme0n1"
    #   - name: "nvme1n1"
    #   - name: "sde"
    #   - name: "sdf"
   #  - name: "dtn2-daejeon.kreonet.net"
   #    devices:
   #    # sda boot  #500GB SSD
   #    # sdb,sdc docker  #2x 1TB SSD
   #    - name: "sdd" #1TB SSD
   #    - name: "sde" #1TB SSD
   #    - name: "sdf" #4TB SATA
   #    - name: "sdg" #4TB SATA
   #    - name: "sdh" #4TB SATA
   #    - name: "sdi" #4TB SATA
   #    - name: "sdj" #4TB SATA
   #    - name: "sdk" #4TB SATA
  # - name: "fiona8.calit2.uci.edu"
  #   devices:
  #   - name: "nvme0n1"
  #   - name: "nvme1n1"
  #   - name: "sdd"
  #   - name: "sde"
  #   - name: "sdf"
  # - name: "prp-dtn.noc.ucsb.edu"
  #   devices:
  #   # sda DEAD
  #   # sdb docker
  #   # sdc boot
  #   # sdd spare SATA DOM
  #   - name: "sde" #10TB 
  #   - name: "sdf" #10TB 
  #   - name: "sdg" #10TB 
  #   - name: "sdh" #10TB 
  #   - name: "sdi" # 128GB ?? Missed a disk
  #   - name: "sdj" #10TB 
  #   - name: "sdk" #10TB 
  #   - name: "sdl" #10TB 
  #   - name: "sdm" #10TB 
  #   - name: "sdn" #10TB 
  #   - name: "sdo" #10TB 
  #   - name: "sdp" #10TB 
  #   - name: "sdq" #10TB 
  #   - name: "sdr" #10TB 
  #   - name: "sds" #10TB 
  #   - name: "sdt" #10TB 
