apiVersion: rook.io/v1alpha1
kind: Pool
metadata:
  name: rbd
  namespace: rook
spec:
  replicated:
    size: 2
  # For an erasure-coded pool, comment out the replication size above and uncomment the following settings.
  # Make sure you have enough OSDs to support the replica size or erasure code chunks.
  erasureCode:
   codingChunks: 2
   dataChunks: 2
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
   name: rook-block
provisioner: rook.io/block
parameters:
  fstype: xfs
  pool: rbd
  # Specify the Rook cluster from which to create volumes. If not specified, it will use `rook` as the namespace and name of the cluster.
  # clusterName: rook
  # clusterNamespace: rook
