apiVersion: ceph.rook.io/v1beta1
kind: ObjectStore
metadata:
  name: rooks3
  namespace: rook
spec:
  metadataPool:
    replicated:
      size: 3
  dataPool:
    erasureCoded:
      dataChunks: 2
      codingChunks: 1
  gateway:
    type: s3
    sslCertificateRef:
    port: 80
    securePort:
    instances: 4
    allNodes: false
    placement:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: env
             operator: In
             values:
             - production
    resources:
     limits:
       memory: "30Gi"
     requests:
       memory: "13Gi"
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rooks3
  namespace: rook
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: s3.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: rook-ceph-rgw-rooks3
          servicePort: 80