cluster_url="nautilus.optiputer.net"

[org]

[org.ucsd]
lat=32.8761
lon=-117.2318
city="San Diego"
state="CA"
description="University of California, San Diego"
domain=["calit2.optiputer.net", "ucsd.edu", "sdsc.optiputer.net"]

[org.caltech]
lat=34.1377
lon=-118.1253
city="Pasadena"
state="CA"
description="California Institute of Technology"
domain=["ultralight.org"]

[org.uci]
lat=33.6488
lon=-117.8407
description="University of California, Irvine"
city="Irvine"
state="CA"
domain=["uci.edu"]

[org.ucsc]
lat=37.0044
lon=-122.0258
city="Santa Cruz"
state="CA"
description="University of California, Santa Cruz"
domain=["ucsc.edu"]

[org.sdsu]
lat=32.7632
lon=-117.0712
city="San Diego"
state="CA"
description="San Diego State University"
domain=["sdsu.edu", "sdsu.optiputer.net"]

[org.stanford]
lat=37.424107
lon=-122.166077
city="Stanford"
state="CA"
description="Stanford University"
domain=["stanford.edu"]

[org.ucr]
lat=33.9533
lon=-117.3962
city="Riverside"
state="CA"
description="University of California, Riverside"
domain=["ucr.edu"]

[org.usc]
lat=34.0224
lon=-118.2851
city="Los Angeles"
state="CA"
description="University of South California"
domain=["usc.edu"]

[org.washington]
lat=47.6553
lon=-122.3035
city="Seattle"
state="WA"
description="University of Washington"
domain=["washington.edu"]

[org.ucdavis]
lat=38.5382
lon=-121.7617
city="Davis"
state="WA"
description="University of California, Davis"
domain=["noc.ucdavis.edu"]

[org.hawaii]
lat=21.2969
lon=-157.8171
city="Honolulu"
state="HI"
description="University of Hawaii"
domain=["hawaii.edu"]

[org.ucarnwsc]
lat=41.1288
lon=-104.8973
city="Cheyenne"
state="WY"
description="NCAR-Wyoming Supercomputing Center"
domain=["nwsc.ucar.edu"]

[org.ucla]
lat=34.0689
lon=-118.4452
city="Los Angeles"
state="CA"
description="University of California, Los Angeles"
domain=["ucla.net"]

[org.ucsb]
lat=34.4140
lon=-119.8489
city="Santa Barbara"
state="CA"
description="University of California, Santa Barbara"
domain=["ucsb.edu"]

[org.kreonet]
lat=36.365717
lon=127.359511
city="Daejeon"
state=""
description="KISTI"
domain=["kreonet.net"]

[org.berkeley]
lat=37.871853
lon=-122.258423
city = "Berkeley"
state="CA"
description="University of California, Berkeley"
domain=["berkeley.edu"]

[org.csusb]
lat=34.182179
lon=-117.323565
city="San Bernerdino"
state="CA"
description="California State University, San Bernardino"
domain=["csusb.edu"]

[org.kc]
lat=39.1008
lon=-94.5832
city="Kansas City"
state="Missoury"
description="University of Missoury, Kansas City"
domain=["greatplains.net"]