apiVersion: v1
kind: ServiceAccount
metadata:
  name: meshconfig-admin
  namespace: perfsonar
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: meshconfig-admin
  namespace: perfsonar
subjects:
- kind: ServiceAccount
  name: meshconfig-admin
  namespace: perfsonar
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    k8s-app: meshconfig-old
  name: meshconfig-old
  namespace: perfsonar
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: meshconfig-old
    spec:
      serviceAccountName: meshconfig-admin
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: meshconfig
        image: us.gcr.io/prp-k8s/meshconfig:latest
        imagePullPolicy: Always
        volumeMounts:
        - name: config-volume
          mountPath: /config
      volumes:
      - name: config-volume
        configMap:
          name: mesh-config
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: meshconfig-old
  name: meshconfig-old
  namespace: perfsonar
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
  selector:
    k8s-app: meshconfig-old
