apiVersion: v1
kind: Pod
metadata:
  name: fs-pod
  namespace: satellite-pwc
spec:
  containers:
  - name: fs-container
    image: ubuntu
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /example-fs
      name: fs-store
  restartPolicy: Never
  volumes:
  - name: fs-store
    flexVolume:
      driver: rook.io/rook
      fsType: ceph
      options:
        fsName: satellite-pwc
        clusterName: rook
