apiVersion: v1
kind: Pod
metadata:
  name: fs-pod
  namespace: dimm
spec:
  containers:
  - name: fs-container
    image: ubuntu
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /example-fs
      name: fs-store
  restartPolicy: Never
  volumes:
  - flexVolume:
      driver: ceph.rook.io/rook
      fsType: ceph
      options:
        clusterNamespace: rook
        fsName: nautilusfs
        path: /dimm
        mountUser: dimm
        mountSecret: ceph-fs-secret
    name: fs-store