apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: default-priority
value: 1000
globalDefault: true
description: "Default"
---
apiVersion: scheduling.k8s.io/v1beta1
kind: PriorityClass
metadata:
  name: suncave-priority
value: 5000
globalDefault: false
description: "Suncave preemtive pods"