kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nautilus-admins
subjects:
- kind: User
  name: http://cilogon.org/serverA/users/15761
  apiGroup: "rbac.authorization.k8s.io"
- kind: User
  name: http://cilogon.org/serverA/users/23651
  apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: psp:nautilus-admins
subjects:
- kind: User
  name: http://cilogon.org/serverA/users/15761
  apiGroup: "rbac.authorization.k8s.io"
- kind: User
  name: http://cilogon.org/serverA/users/23651
  apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: ClusterRole
  name: psp:privileged-user
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:privileged-user
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - privileged
  verbs:
  - use
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: privileged
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'
spec:
  privileged: true
  allowPrivilegeEscalation: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - '*'
  allowedCapabilities:
  - '*'
  hostPorts:
  - min: 0
    max: 65535
  hostPID: true
  hostIPC: true
  hostNetwork: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged-user
subjects:
- namespace: kube-system
  kind: ServiceAccount
  name: default
- namespace: kube-system
  kind: ServiceAccount
  name: kube-proxy
- namespace: kube-system
  kind: ServiceAccount
  name: kube-router
- namespace: kube-dns
  kind: ServiceAccount
  name: kube-router
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:nodes
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:perfsonar
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:monitoring
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:rook
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:rook-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:nautilus-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:nautilus-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:kube-system
