apiVersion: v1
kind: Pod
metadata:
  name: fs-vol-pod-1
  namespace: ucsd-edu
spec:
  containers:
  - name: vol-container
    image: ubuntu
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /examplevol
      name: examplevol
  volumes:
    - name: examplevol
      flexVolume:
        driver: rook.io/rook
        fsType: ceph
        options:
          fsName: myfs # name of the filesystem specified in the filesystem CRD.
          clusterName: rook # namespace where the Rook cluster is deployed
          # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
          # path: /some/path/inside/cephfs
---
apiVersion: v1
kind: Pod
metadata:
  name: fs-vol-pod-2
  namespace: ucsd-edu
spec:
  containers:
  - name: vol-container
    image: ubuntu
    args: ["sleep", "36500000"]
    volumeMounts:
    - mountPath: /examplevol
      name: examplevol
  volumes:
    - name: examplevol
      flexVolume:
        driver: rook.io/rook
        fsType: ceph
        options:
          fsName: myfs # name of the filesystem specified in the filesystem CRD.
          clusterName: rook # namespace where the Rook cluster is deployed
          # by default the path is /, but you can override and mount a specific path of the filesystem by using the path attribute
          # path: /some/path/inside/cephfs
