apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example
spec:
  containers:
  - name: gpu-container
    image: gcr.io/tensorflow/tensorflow:latest-gpu
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /examples
      name: tensor-examples
  volumes:
    - name: tensor-examples
      gitRepo:
        repository: "https://github.com/Hvass-Labs/TensorFlow-Tutorials"
