apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tensorvol
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 200Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: gpu-pod
spec:
  containers:
  - name: gpu-container
    image: gcr.io/tensorflow/tensorflow:latest-gpu
    imagePullPolicy: Always
    #command: ["python"]
    #args: ["-u", "-c", "import tensorflow"]
    args: ["sleep", "36500000"]
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 7
      requests:
        alpha.kubernetes.io/nvidia-gpu: 7
    volumeMounts:
    - name: nvidia-driver-375-66
      mountPath: /usr/local/nvidia
      readOnly: true
    - name: libcuda-so
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so
    - name: libcuda-so-1
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.1
    - name: libcuda-so-375-66
      mountPath: /usr/lib/x86_64-linux-gnu/libcuda.so.375.66/
    - mountPath: /tensorvol
      name: tensorvol
  restartPolicy: Never
  nodeSelector:
    kubernetes.io/hostname: k8s-gpu-01.calit2.optiputer.net
  volumes:
  - name: nvidia-driver-375-66
    hostPath:
      path: /var/lib/nvidia-docker/volumes/nvidia_driver/375.66/
  - name: libcuda-so
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so
  - name: libcuda-so-1
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.1
  - name: libcuda-so-375-66
    hostPath:
      path: /usr/lib/x86_64-linux-gnu/libcuda.so.375.66/
  - name: tensorvol
    persistentVolumeClaim:
      claimName: tensorvol
