apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example
spec:
  containers:
  - name: gpu-container
    image: tensorflow/tensorflow:latest-gpu
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        nvidia.com/gpu: 0
