apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example
spec:
  containers:
  - name: gpu-container
    image: gcr.io/tensorflow/tensorflow:latest-gpu
    imagePullPolicy: Always
    args: ["sleep", "36500000"]
    resources:
      limits:
        alpha.kubernetes.io/nvidia-gpu: 1
      requests:
        alpha.kubernetes.io/nvidia-gpu: 1
    volumeMounts:
    - name: nvidia-driver
      mountPath: /usr/local/nvidia
      readOnly: true
    - mountPath: /examples
      name: tensor-examples
  restartPolicy: Never
  volumes:
    - name: nvidia-driver
      hostPath:
        path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90/
    - name: tensor-examples
      gitRepo:
        repository: "https://github.com/tensorflow/models.git"
