apiVersion: v1
kind: Pod
metadata:
  name: gpu-pod-example
spec:
  containers:
  - name: gpu-container
    image: tensorflow/tensorflow:latest-gpu
    args: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
