apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tools
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tools
    spec:
      containers:
      - name: tools
        image: centos:7
        imagePullPolicy: IfNotPresent
        args: ["sleep", "36500000"]
        securityContext:
          privileged: true
