apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: testvol
  namespace: default
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: tools
  namespace: default
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: tools
    spec:
      containers:
      - name: tools
        image: centos:7
        imagePullPolicy: IfNotPresent
        args: ["sleep", "36500000"]
        # securityContext:
        #   privileged: true
        volumeMounts:
        - mountPath: /testvol
          name: testvol
      volumes:
      - name: testvol
        persistentVolumeClaim:
          claimName: testvol
