# kind: ClusterRole
# apiVersion: rbac.authorization.k8s.io/v1beta1
# metadata:
#   name: cilogon-admin
# rules:
# - apiGroups: ["rbac.authorization.k8s.io"]
#   resources: ["pods"]
#   verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
# ---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: cilogon-admin
subjects:
# - kind: User
#   name: https://test.cilogon.org#http://cilogon.org/serverA/users/15761
#   apiGroup: "rbac.authorization.k8s.io"
- kind: User
  name: https://test.cilogon.org#http://cilogon.org/serverA/users/23651
  apiGroup: "rbac.authorization.k8s.io"
# - kind: User
#   name: https://test.cilogon.org#http://cilogon.org/serverT/users/182183
#   apiGroup: "rbac.authorization.k8s.io"
# - kind: User
#   name: https://test.cilogon.org#http://cilogon.org/serverT/users/182348
#   apiGroup: "rbac.authorization.k8s.io"
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
