FROM sflow/sflow-rt

RUN /sflow-rt/get-app.sh sflow-rt dashboard-example && \
    /sflow-rt/get-app.sh sflow-rt flow-graph && \
    /sflow-rt/get-app.sh sflow-rt top-flows && \
    /sflow-rt/get-app.sh sflow-rt flow-trend && \
    /sflow-rt/get-app.sh sflow-rt svg-weather && \
    /sflow-rt/get-app.sh sflow-rt fabric-view && \
    /sflow-rt/get-app.sh sflow-rt active-routes && \
    /sflow-rt/get-app.sh sflow-rt ix-metrics && \
    /sflow-rt/get-app.sh sflow-rt world-map && \
    /sflow-rt/get-app.sh sflow-rt trace-flow && \
    /sflow-rt/get-app.sh sflow-rt vizceral
