apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: gpu-mon
  namespace: gpu-mon
spec:
  template:
    metadata:
      labels:
        k8s-app: gpu-mon
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: gpu-type
                operator: Exists
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: gpu-mon
        image: us.gcr.io/prp-k8s/gpu-mon:latest
        imagePullPolicy: Always
        command:
          - "/nvidia_exporter"
      tolerations:
      - operator: "Exists"
        key: "nautilus.io/ceph"
        effect: "NoSchedule"          
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: gpu-mon
  name: gpu-mon
  namespace: gpu-mon
spec:
  ports:
  - port: 9114
    targetPort: 9114
    name: exporter
  selector:
    k8s-app: gpu-mon