FROM phusion/baseimage:0.9.19

MAINTAINER Dmitry Mishin <dmishin@sdsc.edu>

RUN apt-get -y update && \
    apt-get -y install screen emacs git python mlocate openmpi-bin openmpi-doc libopenmpi-dev make valgrind g++ m4 gfortran liblapacke-dev libnetcdf-dev iputils-ping openssh-server cmake mesa-utils-extra
