# apiVersion: apps/v1beta1
# kind: Deployment
# metadata:
#   name: paraview
#   namespace: sdsu-edu
# spec:
#   replicas: 1
#   template:
#     metadata:
#       labels:
#         k8s-app: paraview
#     spec:
#       containers:
#       - name: paraview
#         image: phusion/baseimage:0.9.19
#         imagePullPolicy: IfNotPresent
#         args: ["sleep", "36500000"]
#         resources:
#           limits:
#             memory: "12Gi"
#             alpha.kubernetes.io/nvidia-gpu: 2
#           requests:
#             alpha.kubernetes.io/nvidia-gpu: 2
#         volumeMounts:
#         - name: nvidia-driver
#           mountPath: /usr/local/nvidia
#           readOnly: true
#         - name: nfs
#           mountPath: /opt/subflow
#       volumes:
#       - name: nvidia-driver
#         hostPath:
#           path: /var/lib/nvidia-docker/volumes/nvidia_driver/384.90/
#       - name: nfs
#         nfs:
#           server: fiona.sdsu.edu
#           path: "/export/subflow"
# ---
apiVersion: v1
kind: Service
metadata:
  name: paraview
  namespace: sdsu-edu
  labels:
    k8s-app: paraview
spec:
  ports:
  - port: 11111
  type: NodePort
  selector:
    k8s-app: paraview
