apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: subflow
  namespace: sdsu-edu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: subflow
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: subflow
        image: us.gcr.io/prp-k8s/subflow
        imagePullPolicy: IfNotPresent
        args: ["sleep", "36500000"]
