apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: subflow
  namespace: sdsu-edu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: subflow
    spec:
      containers:
      - name: subflow
        image: phusion/baseimage:0.9.19
        imagePullPolicy: IfNotPresent
        args: ["sleep", "36500000"]
        resources:
          limits:
            memory: "16Gi"
        volumeMounts:
        - name: nfs
          mountPath: /opt/subflow
      volumes:
      - name: nfs
        nfs:
          server: fiona.sdsu.edu
          path: "/export/subflow"
