apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavol
  namespace: megulo-abebe
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dhub
  namespace: megulo-abebe
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: dhub
    spec:
      containers:
      - name: dhub
        image: gitlab-registry.nautilus.optiputer.net/prp/dhub
        imagePullPolicy: Always
        args: ["jupyter-notebook", "--allow-root"]
        resources:
          limits:
            memory: "64Gi"
            nvidia.com/gpu: 8
        volumeMounts:
        - name: datavol
          mountPath: /datavol
        - name: nfs
          mountPath: /nfs
      volumes:
      - name: datavol
        persistentVolumeClaim:
          claimName: datavol
      - name: nfs
        nfs:
          server: 10.109.206.102
          path: "/"
---
apiVersion: v1
kind: Service
metadata:
  name: dhub
  namespace: megulo-abebe
  labels:
    k8s-app: dhub
spec:
  ports:
  - port: 8888
  selector:
    k8s-app: dhub
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: megulo-abebe
  namespace: megulo-abebe
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: megulo.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: dhub
          servicePort: 8888