apiVersion: v1
kind: ServiceAccount
metadata:
  name: es-priv
  namespace: fluentd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: es-privileged
  namespace: fluentd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:privileged-user
subjects:
- kind: ServiceAccount
  name: es-priv
  namespace: fluentd
