apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: fluentd
  labels:
    component: elasticsearch
    role: data
spec:
  selector:
    component: elasticsearch
    role: data
  ports:
  - name: http
    port: 9200
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-discovery
  namespace: fluentd
  labels:
    component: elasticsearch
    role: master
spec:
  selector:
    component: elasticsearch
    role: master
  ports:
  - name: transport
    port: 9300
    protocol: TCP
  clusterIP: None