apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: psp:osg-user
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - osgpolicy
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: psp:osg-user
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: psp:osg-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:osg
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: osgpolicy
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - NET_ADMIN
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 65536
    min: 1024
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowedHostPaths:
  - pathPrefix: "/data1"
  hostNetwork: true
  volumes:
  - configMap
  - emptyDir
  - secret
  - nfs
  - downwardAPI
  - persistentVolumeClaim
  - hostPath