apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cassandra-mon
  namespace: monitoring
  labels:
    k8s-app: esmond-cassandra
spec:
  selector:
    matchLabels:
      k8s-app: esmond-cassandra
  namespaceSelector:
    matchNames:
    - perfsonar
  endpoints:
  - port: exporter
    interval: 10s        # scrape the endpoint every 10 seconds
    path: /metrics
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: prometheus-k8s
  namespace: perfsonar
rules:
- apiGroups: [""]
  resources:
  - services
  - endpoints
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: prometheus-k8s
  namespace: perfsonar
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: prometheus-k8s
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring