apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: perfsonar-toolkit
  namespace: kube-public
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: perfsonar-toolkit
    spec:
      # hostNetwork: true
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: perfsonar-toolkit
        image: us.gcr.io/prp-k8s/perfsonar-toolkit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 443
        command:
          - "/bin/bash"
          - "-c"
          # - "source /etc/profile.d/esmond.sh && export && /startfoo.sh && /usr/sbin/apachectl -DFOREGROUND"
          # - "/usr/sbin/apachectl -DFOREGROUND"
          # - "sleep 365000000"
          # - "source /etc/profile.d/esmond.sh && export && /startfoo.sh && /usr/sbin/apachectl -DFOREGROUND"
          - "/usr/bin/supervisord -c /etc/supervisor-config/supervisord.conf"
        volumeMounts:
        - name: ssl-key
          mountPath: /etc/pki/tls/mycert
        - name: supervisor-config
          mountPath: /etc/supervisor-config
      nodeSelector:
        kubernetes.io/hostname: ps-100g.sdsu.edu
      volumes:
        - name: supervisor-config
          configMap:
            name: perfsonar-supervisor
        - name: ssl-key
          secret:
            secretName: ssl-key
            defaultMode: 256
            items:
              - key: key
                path: localhost.key
              - key: cert
                path: localhost.crt
---
apiVersion: v1
kind: Service
metadata:
  name: perfsonar-toolkit
  namespace: kube-public
  labels:
    k8s-app: perfsonar-toolkit
spec:
  ports:
  - port: 443
  type: NodePort
  selector:
    k8s-app: perfsonar-toolkit
