apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: perfsonar-toolkit
  namespace: kube-public
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: perfsonar-toolkit
    spec:
      imagePullSecrets:
        - name: gcr-json-key
      containers:
      - name: perfsonar-toolkit
        image: us.gcr.io/prp-k8s/perfsonar-toolkit:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        command:
          - "/bin/bash"
          - "-c"
          # - "source /etc/profile.d/esmond.sh && export && /startfoo.sh && /usr/sbin/apachectl -DFOREGROUND"
          - "/usr/sbin/apachectl -DFOREGROUND"
      nodeSelector:
        kubernetes.io/hostname: ps-100g.sdsu.edu
---
apiVersion: v1
kind: Service
metadata:
  name: perfsonar-toolkit
  namespace: kube-public
  labels:
    k8s-app: perfsonar-toolkit
spec:
  ports:
  - port: 80
  type: NodePort
  selector:
    k8s-app: perfsonar-toolkit
