kind: Pod
apiVersion: v1
metadata:
  name: esmond-postgres
  namespace: kube-public
  labels:
    name: esmond-postgres
spec:
  containers:
  - name: esmond-postgres
    securityContext:
      privileged: false
    image: crunchydata/crunchy-postgres:centos7-9.6-1.5
    readinessProbe:
      exec:
        command:
        - "/opt/cpm/bin/readiness.sh"
      initialDelaySeconds: 10
      timeoutSeconds: 1
    livenessProbe:
      exec:
        command:
        - "/opt/cpm/bin/liveness.sh"
      initialDelaySeconds: 120
      timeoutSeconds: 1
    ports:
    - containerPort: 5432
      protocol: TCP
    env:
    - name: PG_MASTER_USER
      value: master
    - name: PG_MASTER_PORT
      value: '5432'
    - name: PGHOST
      value: "/tmp"
    - name: PG_MODE
      value: master
    - name: PG_MASTER_PASSWORD
      value: password
    - name: PG_USER
      value: esmond
    - name: PG_PASSWORD
      value: esmond
    - name: PG_DATABASE
      value: esmond
    - name: PG_ROOT_PASSWORD
      value: password
    volumeMounts:
    - mountPath: "/pgdata"
      name: pgdata
      readOnly: false
    - mountPath: "/backup"
      name: backup
      readOnly: true
  volumes:
  - name: pgdata
    emptyDir: {}
  - name: backup
    emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: esmond-postgres
  namespace: kube-public
  labels:
    name: esmond-postgres
spec:
  ports:
  - protocol: TCP
    port: 5432
  selector:
    name: esmond-postgres
  type: ClusterIP
  sessionAffinity: None
