apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: kube-public
  labels:
    app: globus-connect-server
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
