apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: globus
  labels:
    app: globus-connect-server
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
Johns-Air-3:globus-connect johng$ cat globus-connect-server.yaml
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: globus-connect-server
  namespace: globus
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: globus-connect-server
    spec:
      containers:
      - name: globus-connect-server
        image: gateway.calit2.optiputer.net:5000/prp-k8s/globus-connect:latest
        imagePullPolicy: Always
        args: ["/usr/sbin/globus-gridftp-server", "-c", "/etc/gridftp.conf", "-pidfile", "/var/run/globus-gridftp-server.pid", "-no-detach", "-config-base-path", "/data"]
        volumeMounts:
            - mountPath: /home/data
              name: data
      volumes:
          - name: data
            persistentVolumeClaim:
              claimName: data
      nodeSelector:
        kubernetes.io/hostname: ps-100g.sdsu.edu
---
apiVersion: v1
kind: Service
metadata:
  name: globus-connect-server
  namespace: globus
  labels:
    k8s-app: globus-connect-server
spec:
  ports:
  - port: 2811
  type: NodePort
  selector:
    k8s-app: globus-connect-server
  - port: 50000-51000
  type: NodePort
  selector:
    k8s-app: globus-connect-server