apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: grafana.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: grafana
          servicePort: 3000
