# traefik.toml
InsecureSkipVerify = true
defaultEntryPoints = ["http","https"]
[entryPoints]
  [entryPoints.http]
  address = ":80"
    [entryPoints.http.redirect]
      entryPoint = "https"
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      CertFile = "/ssl/k8s_cert.cer"
      KeyFile = "/ssl/k8s.key"
[web]
  CertFile = "/ssl/k8s_cert.cer"
  KeyFile = "/ssl/k8s.key"
  address = ":8081"
  readOnly = true
  [web.auth.basic]
  users = ["admin:$apr1$iDCPy4sV$AX7/4homFxf.DLDWPMIPU0"]
