apiVersion: v1
kind: Secret
metadata:
  name: nextcloud
  namespace: nextcloud
data:
  dbusername: ""
  dbpassword: ""
  dbname: ""
  username: ""
  password: ""
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloudvol
  namespace: nextcloud
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 4Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextclouddbvol
  namespace: nextcloud
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  selector:
    matchLabels:
      k8s-app: nextcloud
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: nextcloud
    spec:
      initContainers:
        - name: config-data
          image: busybox
          command: ["chown", "33:33", "/var/lib/nextcloud", "-R"]
          volumeMounts:
            - mountPath: /var/lib/nextcloud
              name: data
      containers:
        - name: mysql
          image: sameersbn/mysql
          env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: dbusername
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: dbpassword
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: dbname
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: dbdata
        - name: nextcloud
          image: nextcloud
          env:
            - name: TZ
              value: America/Los_Angeles
            - name: DEBUG
              value: "false"

            - name: NEXTCLOUD_URL
              value: http://nextcloud.k8s.optiputer.net

            - name: NEXTCLOUD_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: username
            - name: NEXTCLOUD_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: password

            - name: NEXTCLOUD_UPLOAD_MAX_FILESIZE
              value: 36G
            - name: NEXTCLOUD_MAX_FILE_UPLOADS
              value: "20"

            - name: MYSQL_HOST
              value: 127.0.0.1
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: dbusername
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: dbpassword
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: nextcloud
                  key: dbname
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
            - mountPath: /var/www/html
              name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: nextcloudvol
        - name: dbdata
          persistentVolumeClaim:
            claimName: nextclouddbvol
---
apiVersion: v1
kind: Service
metadata:
  name: nextcloud
  namespace: nextcloud
  labels:
    k8s-app: nextcloud
spec:
  type: NodePort
  ports:
    - name: web
      port: 80
      protocol: TCP
  selector:
    k8s-app: nextcloud
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nextcloud
  namespace: nextcloud
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: nextcloud.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: nextcloud
          servicePort: 80
