apiVersion: v1
kind: ServiceAccount
metadata:
  name: build-robot
  namespace: gitlab-managed-apps
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-helm
  namespace: gitlab-managed-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- namespace: gitlab
  kind: ServiceAccount
  name: build-robot
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: build-robot
  namespace: gitlab-managed-apps
rules:
- apiGroups:
  - "*"
  - extensions
  resources:
  - 'namespace'
  verbs:
  - 'list'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: build-robot
  namespace: gitlab-managed-apps
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: build-robot
subjects:
- namespace: gitlab-managed-apps
  kind: ServiceAccount
  name: build-robot
