[sysctl]
"fs.file-max"="800000"
"fs.aio-max-nr"="1048576"
"net.core.default_qdisc"="fq"
"net.core.rmem_max"="536870912"
"net.core.wmem_max"="536870912"
"net.ipv4.tcp_rmem"="4096\t87380\t268435456"
"net.ipv4.tcp_wmem"="4096\t65536\t268435456"
"net.core.netdev_max_backlog"="250000"
"net.ipv4.tcp_congestion_control"="htcp"
"net.ipv4.tcp_mtu_probing"="1"
"net.ipv4.tcp_no_metrics_save"="1"
"net.ipv4.tcp_timestamps"="1"
"net.ipv4.tcp_sack"="1"
"net.ipv4.tcp_low_latency"="0"