apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: psp:sdsu-user
  namespace: sdsu
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - sdsupolicy
  verbs:
  - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: psp:sdsu-user
  namespace: sdsu
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: psp:sdsu-user
subjects:
- apiGroup: rbac.authorization.k8s.io
  kind: Group
  name: system:serviceaccounts:default
---
apiVersion: extensions/v1beta1
kind: PodSecurityPolicy
metadata:
  name: sdsupolicy
  namespace: sdsu
spec:
  allowPrivilegeEscalation: false
  allowedCapabilities:
  - NET_ADMIN
  fsGroup:
    rule: RunAsAny
  hostPorts:
  - max: 65536
    min: 1024
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  allowedHostPaths:
  - pathPrefix: "/mnt/beegfs/home/k8s"
  hostNetwork: false
  volumes:
  - configMap
  - emptyDir
  - secret
  - nfs
  - downwardAPI
  - persistentVolumeClaim
  - hostPath