# mongo -u $MONGO_INITDB_ROOT_USERNAME -p $MONGO_INITDB_ROOT_PASSWORD --ssl --sslAllowInvalidHostnames --sslAllowInvalidCertificates --authenticationDatabase=admin
# use rocketchat
# db.createUser({user: 'rocketchat', pwd: '', roles:[{role:'dbOwner', db:'rocketchat'}]})
apiVersion: v1
kind: Secret
metadata:
  name: mongodb
  namespace: rocketchat
data:
  username: "cm9ja2V0Y2hhdA=="
  password: ""
  database: "cm9ja2V0Y2hhdA=="
  connectstring: ""
  #"mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@127.0.0.1:27017/${MONGODB_DATABASE}"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: rocketchat
  labels:
    k8s-app: mongo
spec:
  ports:
  - port: 27017
    targetPort: 27017
  clusterIP: None
  selector:
    k8s-app: mongo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
  namespace: rocketchat
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi