{
 "title": "All Cuda GPU",
 "description": "Graph CUDA GPU statistics",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "node",
    "label": "server",
    "query": "label_values(nvml_gpu_percent, instance)"
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Total Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(nvml_gpu_percent{instance=~\"$node\"})/count(nvml_gpu_percent{instance=~\"$node\"})",
     "legendFormat": "GPU"
    },
    {
     "expr": "sum(nvml_memory_percent{instance=~\"$node\"})/count(nvml_memory_percent{instance=~\"$node\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Total power draw",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "expr": "sum(nvml_power_watts{instance=~\"$node\"})",
     "legendFormat": "All cores"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "max(nvml_temperature_celsius{instance=~\"$node\"})",
     "legendFormat": "Temperature"
    }
   ]
  }
 ]
}