apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webodm
  namespace: ucsd-edu
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webodm
  namespace: ucsd-edu
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: webodm
    spec:
      containers:
      - name: db
        image: opendronemap/webodm_db
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: webodmpv
      - name: webapp
        image: opendronemap/webodm_webapp
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh"]
        args: ["-c", "sed -i \"s/'db'/'localhost'/g\" /webodm/webodm/settings.py && chmod +x /webodm/*.sh && /webodm/wait-for-it.sh localhost:5432 -- /webodm/start.sh"]
      volumes:
      - name: webodmpv
        persistentVolumeClaim:
          claimName: webodm
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: webodm
  name: webodm
  namespace: ucsd-edu
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
  selector:
    k8s-app: webodm
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webodm
  namespace: ucsd-edu
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: webodm.k8s.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: webodm
          servicePort: 80
