# # Nodes: webodmnode-0.webodmnode.webodm.svc.cluster.local
# # examples https://github.com/OpenDroneMap/odm_data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webodmdb
  namespace: webodm
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webodmmedia
  namespace: webodm
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: webodm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: redis
    spec:
      containers:
      - name: redis
        image: redis
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webodm
  namespace: webodm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: webodm
    spec:
      containers:
      - name: db
        image: opendronemap/webodm_db
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: webodmdb
      - name: webapp
        image: opendronemap/webodm_webapp
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sed -i \"s/'db'/'webodmdb'/g\" /webodm/webodm/settings.py && chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh webodmdb /webodm/wait-for-it.sh redis:6379 -- /webodm/start.sh\""]
        volumeMounts:
        - mountPath: /webodm/app/media
          name: webodmmedia
        env:
        - name: WO_BROKER
          value: "redis://redis"
      volumes:
      - name: webodmdb
        persistentVolumeClaim:
          claimName: webodmdb
      - name: webodmmedia
        persistentVolumeClaim:
          claimName: webodmmedia
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: webodm
  name: webodm
  namespace: webodm
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    name: web
  selector:
    k8s-app: webodm
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: webodm
  name: webodmdb
  namespace: webodm
spec:
  ports:
  - port: 5432
    targetPort: 5432
    name: db
  selector:
    k8s-app: webodm
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: redis
  name: redis
  namespace: webodm
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  selector:
    k8s-app: redis
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: webodmnode
  namespace: webodm
spec:
  podManagementPolicy: Parallel
  serviceName: webodmnode
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: webodmnode
    spec:
      containers:
      - name: node-odm
        image: opendronemap/webodm_webapp
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sed -i \"s/'db'/'webodmdb'/g\" /webodm/webodm/settings.py && /webodm/wait-for-postgres.sh webodmdb /webodm/wait-for-it.sh redis:6379 -- /webodm/worker.sh start"]
        env:
        - name: WO_BROKER
          value: "redis://redis"
        resources:
          limits:
            memory: "40Gi"
        volumeMounts:
        - name: webodm-node-data
          mountPath: /webodm/app/media
  volumeClaimTemplates:
  - metadata:
      name: webodm-node-data
      annotations:
        volume.beta.kubernetes.io/storage-class: rook-block
    spec:
      storageClassName: rook-block
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 150Gi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: webodmnode
  name: webodmnode
  namespace: webodm
spec:
  clusterIP: None
  ports:
  - port: 3000
    name: web
  selector:
    k8s-app: webodmnode
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webodm
  namespace: webodm
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: webodm.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: webodm
          servicePort: 80
