# # Nodes: webodmnode-0.webodmnode.webodm.svc.cluster.local
# # examples https://github.com/OpenDroneMap/odm_data
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webodmdb
  namespace: webodm
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webodmmedia
  namespace: webodm
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: webodm
  namespace: webodm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: webodm
    spec:
      containers:
      - name: db
        image: opendronemap/webodm_db
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: webodmdb
      - name: webapp
        image: opendronemap/webodm_webapp
        imagePullPolicy: Always
        command: ["/bin/sh"]
        args: ["-c", "sed -i \"s/'db'/'localhost'/g\" /webodm/webodm/settings.py && chmod +x /webodm/*.sh && /webodm/wait-for-it.sh localhost:5432 -- /webodm/start.sh"]
        volumeMounts:
        - mountPath: /webodm/app/media
          name: webodmmedia
      volumes:
      - name: webodmdb
        persistentVolumeClaim:
          claimName: webodmdb
      - name: webodmmedia
        persistentVolumeClaim:
          claimName: webodmmedia
---
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: webodm
  name: webodm
  namespace: webodm
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8000
    name: web
  selector:
    k8s-app: webodm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: webodmnode
  namespace: webodm
spec:
  podManagementPolicy: Parallel
  serviceName: webodmnode
  replicas: 2
  template:
    metadata:
      labels:
        k8s-app: webodmnode
    spec:
      containers:
      - name: node-odm
        image: opendronemap/node-opendronemap
        imagePullPolicy: Always
        resources:
          limits:
            memory: "40Gi"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: webodmnode
  name: webodmnode
  namespace: webodm
spec:
  clusterIP: None
  ports:
  - port: 3000
  selector:
    k8s-app: webodmnode
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: webodm
  namespace: webodm
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: webodm.nautilus.optiputer.net
    http:
      paths:
      - path: /
        backend:
          serviceName: webodm
          servicePort: 80
