apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavol
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dhub
  namespace: digital-humanities
spec:
  replicas: 3
  template:
    metadata:
      labels:
        k8s-app: dhub
    spec:
      containers:
      - name: dhub
        image: gcr.io/tensorflow/tensorflow:latest-gpu
        imagePullPolicy: Always
        args: ["sleep", "36500000"]
        resources:
          limits:
            memory: "12Gi"
            nvidia.com/gpu: 2
        volumeMounts:
        - name: datavol
        mountPath: /datavol
      restartPolicy: Never
      volumes:
      - name: datavol
        persistentVolumeClaim:
          claimName: datavol
