apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datavol
  namespace: digital-humanities
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 512Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: dhub
  namespace: digital-humanities
spec:
  replicas: 1
  template:
    metadata:
      labels:
        k8s-app: dhub
    spec:
      containers:
      - name: dhub
        image: us.gcr.io/prp-k8s/dhub
        imagePullPolicy: Always
        args: ["sleep", "36500000"]
        resources:
          limits:
            memory: "12Gi"
            nvidia.com/gpu: 2
        volumeMounts:
        - name: datavol
          mountPath: /datavol
      volumes:
      - name: datavol
        persistentVolumeClaim:
          claimName: datavol
---
apiVersion: v1
kind: Service
metadata:
  name: dhub
  namespace: digital-humanities
  labels:
    k8s-app: dhub
spec:
  ports:
  - port: 8000
  selector:
    k8s-app: dhub
