apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: testpoint
  namespace: kube-public
spec:
  template:
    metadata:
      labels:
        k8s-app: testpoint
    spec:
      initContainers:
      - name: config-mount
        image: busybox
        command: ["sh", "-c", "chown -R 999:1000 /etc/perfsonar/meshconfig-agent*"]
        volumeMounts:
        - name: config
          mountPath: /etc/perfsonar/meshconfig-agent-tasks.conf
          subPath: meshconfig-agent-tasks.conf
        - name: config
          mountPath: /etc/perfsonar/meshconfig-agent.conf
          subPath: meshconfig-agent.conf
      containers:
      - name: testpoint
        image: us.gcr.io/prp-k8s/perfsonar_testpoint:latest
        imagePullPolicy: Always
        # args: ["/usr/sbin/apachectl", "-DFOREGROUND"]
        command:
          - "/usr/bin/supervisord"
          - "-c"
          - "/etc/supervisord.conf"
        volumeMounts:
        - name: config
          mountPath: /etc/perfsonar/meshconfig-agent-tasks.conf
          subPath: meshconfig-agent-tasks.conf
        - name: config
          mountPath: /etc/perfsonar/meshconfig-agent.conf
          subPath: meshconfig-agent.conf
      volumes:
      - name: config
        configMap:
          name: perfsonar-testpoint
---
apiVersion: v1
kind: Service
metadata:
  name: testpoint
  namespace: kube-public
  labels:
    k8s-app: testpoint
spec:
  ports:
  - port: 80
  type: NodePort
  selector:
    k8s-app: testpoint
