apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kube-registry-pvc
  namespace: gitlab
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab
  namespace: gitlab
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-db
  namespace: gitlab
spec:
  storageClassName: rook-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gitlab
  namespace: gitlab
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gitlab
        app: gitlab
    spec:
      containers:
      - name: gitlab
        image: sameersbn/gitlab:11.4.5
        # imagePullPolicy: Always
        resources:
          requests:
            memory: "6Gi"
          limits:
            memory: "10Gi"
        env:
        - name: TZ
          value: America/Los_Angeles
        - name: GITLAB_TIMEZONE
          value: "Pacific Time (US & Canada)"
        - name: DEBUG
          value: "true"

        - name: GITLAB_SECRETS_DB_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: dbkey
        - name: GITLAB_SECRETS_SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: secretkey
        - name: GITLAB_SECRETS_OTP_KEY_BASE
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: otpkey

        - name: GITLAB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: rootpw
        - name: GITLAB_ROOT_EMAIL
          value: dmishin@ucsd.edu

        - name: GITLAB_HTTPS
          value: "true"
        - name: GITLAB_HOST
          value: gitlab.nautilus.optiputer.net
        - name: GITLAB_PORT
          value: "443"
        - name: GITLAB_SSH_HOST
          value: "gitlab-ssh.nautilus.optiputer.net"
        - name: GITLAB_SSH_PORT
          value: "30622"

        - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
          value: "true"
        - name: GITLAB_NOTIFY_PUSHER
          value: "false"

        - name: GITLAB_BACKUP_SCHEDULE
          value: "weekly"

        - name: GCS_BACKUPS
          value: "true"
        - name: GCS_BACKUP_BUCKET
          value: "nautilus-gitlab"
        - name: GCS_BACKUP_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: gcpkey
        - name: GCS_BACKUP_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: gcpsecret

        - name: GITLAB_REGISTRY_ENABLED
          value: "true"
        - name: GITLAB_REGISTRY_HOST
          value: gitlab-registry.nautilus.optiputer.net
        - name: GITLAB_REGISTRY_PORT
          value: "443"
        - name: GITLAB_REGISTRY_API_URL
          value: https://gitlab-registry.nautilus.optiputer.net
        - name: GITLAB_REGISTRY_KEY_PATH
          value: /home/git/data/certs/registry.key
        - name: GITLAB_REGISTRY_ISSUER
          value: gitlab-issuer

        - name: DB_TYPE
          value: postgres
        - name: DB_HOST
          value: 127.0.0.1
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: dbpw
        - name: DB_NAME
          value: gitlab_production

        - name: REDIS_HOST
          value: 127.0.0.1
        - name: REDIS_PORT
          value: "6379"

        # - name: OAUTH_ENABLED
        #   value: "true"
        # - name: OAUTH_EXTERNAL_PROVIDERS
        #   value: "gitlab"

        - name: OAUTH_GITLAB_API_KEY
          valueFrom:
            secretKeyRef:
              name: gitlab-oauth
              key: key
        - name: OAUTH_GITLAB_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: gitlab-oauth
              key: secret

        - name: OAUTH_GITHUB_API_KEY
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: key
        - name: OAUTH_GITHUB_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: github-oauth
              key: secret

        - name: OAUTH_GOOGLE_API_KEY
          valueFrom:
            secretKeyRef:
              name: google-oauth
              key: key
        - name: OAUTH_GOOGLE_APP_SECRET
          valueFrom:
            secretKeyRef:
              name: google-oauth
              key: secret


        - name: SMTP_ENABLED
          value: "true"
        - name: SMTP_DOMAIN
          value: ucsd.edu
        - name: SMTP_HOST
          value: smtp.ucsd.edu
        - name: SMTP_PORT
          value: "465"
        - name: SMTP_USER
          value: nautilus@eng.ucsd.edu
        - name: SMTP_STARTTLS
          value: "false"
        - name: SMTP_TLS
          value: "true"
        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              key: smtppw
              name: gitlab
        - name: IMAP_ENABLED
          value: "false"
        - name: IMAP_HOST
          value: imap.gmail.com
        - name: IMAP_PORT
          value: "993"
        - name: IMAP_USER
          value: mailer@example.com
        - name: IMAP_PASS
          value: password
        - name: IMAP_SSL
          value: "true"
        - name: IMAP_STARTTLS
          value: "false"
        ports:
        - name: http
          containerPort: 80
        - name: ssh
          containerPort: 22
        volumeMounts:
        - mountPath: /home/git/data
          name: data
        - name: image-store
          mountPath: /home/git/data/shared/registry
        - mountPath: "/home/git/data/certs"
          name: "ssl"
        # livenessProbe:
        #   httpGet:
        #     path: /users/sign_in
        #     port: 80
        #   initialDelaySeconds: 360
        #   timeoutSeconds: 15
        # readinessProbe:
        #   httpGet:
        #     path: /users/sign_in
        #     port: 80
        #   initialDelaySeconds: 45
        #   timeoutSeconds: 1
      - name: registry
        image: registry
        resources:
          requests:
            memory: "6Gi"
          limits:
            memory: "10Gi"
        env:
        - name: REGISTRY_HTTP_ADDR
          value: 0.0.0.0:5000
        - name: REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY
          value: /var/lib/registry
        - name: REGISTRY_AUTH_TOKEN_SERVICE
          value: container_registry
        - name: REGISTRY_AUTH_TOKEN_REALM
          value: https://gitlab.nautilus.optiputer.net/jwt/auth
        - name: REGISTRY_AUTH_TOKEN_ISSUER
          value: gitlab-issuer
        - name: REGISTRY_LOG_LEVEL
          value: debug
        - name: REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE
          value: /ssl/registry.crt
        - name: REGISTRY_STORAGE_DELETE_ENABLED
          value: "true"
        volumeMounts:
        - name: image-store
          mountPath: /var/lib/registry
        - mountPath: "/ssl"
          name: "ssl"
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
      - name: postgresql
        image: sameersbn/postgresql
        imagePullPolicy: Always
        env:
        - name: DB_USER
          value: gitlab
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: gitlab
              key: dbpw
        - name: DB_NAME
          value: gitlab_production
        - name: DB_EXTENSION
          value: pg_trgm
        ports:
        - name: postgres
          containerPort: 5432
        volumeMounts:
        - mountPath: /var/lib/postgresql
          name: db-data
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -h
            - localhost
            - -U
            - postgres
          initialDelaySeconds: 5
          timeoutSeconds: 1
      - name: redis
        image: redis
        volumeMounts:
          - mountPath: /var/lib/redis
            name: redisdata
        livenessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          exec:
            command:
              - redis-cli
              - ping
          initialDelaySeconds: 5
          timeoutSeconds: 1
      tolerations:
      - operator: "Exists"
        key: "nautilus.io/ceph"
        effect: "NoSchedule" 
      - operator: "Exists"
        key: "nautilus.io/science-dmz"
        effect: "NoSchedule"          
      volumes:
      - name: ssl
        secret:
          secretName: ssl-key
      - name: data
        persistentVolumeClaim:
          claimName: gitlab
      - name: image-store
        persistentVolumeClaim:
          claimName: kube-registry-pvc
      - name: db-data
        persistentVolumeClaim:
          claimName: gitlab-db
      - name: redisdata
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab
  namespace: gitlab
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
  - port: 5000
    targetPort: 5000
    protocol: TCP
    name: registry
  selector:
    name: gitlab
---
apiVersion: v1
kind: Service
metadata:
  name: gitlab-ssh
  namespace: gitlab
spec:
  type: NodePort
  ports:
  - nodePort: 30622
    port: 22
    protocol: TCP
    name: ssh
  selector:
    name: gitlab