apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tiller-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
subjects:
- kind: ServiceAccount
  name: tiller
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mpi-default
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods", "configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mpi-default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mpi-default
subjects:
- kind: ServiceAccount
  name: default
